version: "3.9"

services:
  travel-buddy:
    build: .
    container_name: travel-buddy-agent
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
