name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Extract short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build . -t my-image-name:${SHORT_SHA}

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan Docker image with Trivy
      run: trivy image --exit-code 1 --severity HIGH,CRITICAL my-image-name:${SHORT_SHA}

